name: Deploy to Pantheon

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Pantheon environment
      run: echo "PANTHEONENV=dev" >> $GITHUB_ENV  # Replace 'dev' with your environment

    - name: Install Terminus
      run: curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar && php installer.phar install

    - name: Install Terminus Rsync Plugin
      run: terminus self:plugin:install pantheon-systems/terminus-rsync-plugin

    - name: Authenticate with Pantheon
      run: terminus auth:login --machine-token=${{ secrets.PANTHEON_TERMINUS_MACHINE_TOKEN }}

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PANTHEON_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H appserver.dev.6ddd6e77-4220-4883-a433-d26c18c83e68.drush.in >> ~/.ssh/known_hosts

    - name: Start SSH agent and add key with passphrase
      run: |
        eval $(ssh-agent -s)
        echo "${{ secrets.PANTHEON_SSH_KEY_PASSPHRASE }}" | ssh-add ~/.ssh/id_rsa
      env:
        SSH_ASKPASS: /bin/echo

    - name: Verify SSH Connection
      run: ssh -o StrictHostKeyChecking=no -p 2222 dev.6ddd6e77-4220-4883-a433-d26c18c83e68@appserver.dev.6ddd6e77-4220-4883-a433-d26c18c83e68.drush.in "echo SSH connection successful"

    - name: Deploy Code to Pantheon
      run: |
        terminus connection:set geeva-test.$PANTHEONENV sftp
        rsync -rlvz --size-only --ipv4 -e 'ssh -p 2222' ./code/ dev.6ddd6e77-4220-4883-a433-d26c18c83e68@appserver.dev.6ddd6e77-4220-4883-a433-d26c18c83e68.drush.in:code/

    - name: Clear Pantheon Cache
      run: terminus env:clear-cache geeva-test.$PANTHEONENV
