name: Pantheon Build
on:
  push:
    branches:
      - master

jobs:
  github_deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Pantheon Deploy
      uses: pantheoncarl/pantheon-deploy@master
      id: cache-vendor
      env:
        PANTHEONSITEUUID: 6ddd6e77-4220-4883-a433-d26c18c83e68
        PANTHEON_TERMINUS_MACHINE_TOKEN: ${{ secrets.PANTHEON_TERMINUS_MACHINE_TOKEN }}
        PANTHEON_PRIVATE_KEY: ${{ secrets.PANTHEON_PRIVATE_KEY }}
