name: Pantheon Build
on:
  push:
    branches:
      - master

jobs:
  github_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PANTHEON_GITHUB_ACTIONS_DEPLOY_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -t rsa pantheon.io >> ~/.ssh/known_hosts
    - name: Pantheon Deploy
      uses: pantheoncarl/pantheon-deploy@main
      id: cache-vendor
      env:
        PANTHEONSITEUUID: 6ddd6e77-4220-4883-a433-d26c18c83e68
        PANTHEON_TERMINUS_MACHINE_TOKEN: ${{ secrets.PANTHEON_TERMINUS_MACHINE_TOKEN }}
        PANTHEON_PRIVATE_KEY: ${{ secrets.PANTHEON_GITHUB_ACTIONS_DEPLOY_KEY }}
        PANTHEONENV: dev  # Set your environment value here
