name: Deploy to Pantheon

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Pantheon environment
      run: echo "PANTHEONENV=dev" >> $GITHUB_ENV  # Replace 'dev' with your environment

    - name: Install Terminus
      run: |
        curl -O https://raw.githubusercontent.com/pantheon-systems/terminus-installer/master/builds/installer.phar
        php installer.phar install

    - name: Install Terminus Rsync Plugin
      run: terminus self:plugin:install pantheon-systems/terminus-rsync-plugin

    - name: Authenticate with Pantheon
      run: terminus auth:login --machine-token=${{ secrets.PANTHEON_TERMINUS_MACHINE_TOKEN }}

    - name: Set up SSH key
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.PANTHEON_PRIVATE_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -H appserver.dev.6ddd6e77-4220-4883-a433-d26c18c83e68.drush.in >> ~/.ssh/known_hosts
        echo "Contents of id_rsa:"
        cat ~/.ssh/id_rsa  # Debugging: Show SSH key content
        echo "Contents of known_hosts:"
        cat ~/.ssh/known_hosts  # Debugging: Show known hosts content
        ls -l ~/.ssh  # Debugging: List files in .ssh directory
      env:
        PANTHEON_PRIVATE_KEY: ${{ secrets.PANTHEON_PRIVATE_KEY }}
      shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}

    - name: Start SSH agent and add key with passphrase
      run: |
        eval $(ssh-agent -s)
        echo "${{ secrets.PANTHEON_SSH_KEY_PASSPHRASE }}" | ssh-add ~/.ssh/id_rsa
        ssh-add -l  # Debugging: List loaded SSH keys
      env:
        SSH_ASKPASS: /bin/echo
      shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}

    - name: Verify SSH Connection
      run: |
        ssh -vvv -o StrictHostKeyChecking=no -p 2222 dev.6ddd6e77-4220-4883-a433-d26c18c83e68@appserver.dev.6ddd6e77-4220-4883-a433-d26c18c83e68.drush.in "echo SSH connection successful"
      shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}

    - name: Deploy Code to Pantheon
      run: |
        terminus connection:set ${{ secrets.PANTHEON_SITE_NAME }}.$PANTHEONENV sftp
        rsync -rlvz --size-only --ipv4 -e 'ssh -p 2222' ./code/ dev.6ddd6e77-4220-4883-a433-d26c18c83e68@appserver.dev.6ddd6e77-4220-4883-a433-d26c18c83e68.drush.in:code/
      shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}

    - name: Clear Pantheon Cache
      run: terminus env:clear-cache ${{ secrets.PANTHEON_SITE_NAME }}.$PANTHEONENV
      shell: /usr/bin/bash --noprofile --norc -e -o pipefail {0}
